[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wiithon"
description = "Wii ISO reading, patching and rebuilding library"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
authors = [{ name = "demorck" }]
keywords = [
    "wii", "nintendo",
    "iso", "rom-hacking", "patching", "reverse-engineering",
    "dol", "rarc", "bcsv", "u8", "lz77", "bnr"]

dynamic = ["version"]

classifiers = [
    "Development Status :: 3 - Alpha",

    "Intended Audience :: Developers",

    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    "Topic :: Software Development :: Disassemblers",
    "Topic :: Games/Entertainment",
    "Topic :: System :: Archiving",
    "Topic :: File Formats",

    "Typing :: Typed",
]

requires-python = ">=3.11"
dependencies = [
    "pycryptodome>=3.0",
    "typer>=0.9",
    "rich>=13.0",
]

[project.urls]
Homepage = "https://github.com/Demorck/wiithon"
Issues = "https://github.com/Demorck/wiithon/issues"
Documentation = "https://demorck.github.io/wiithon/"

[project.scripts]
wiithon = "wiithon.cli:app"

[project.optional-dependencies]
dev = ["pytest>=8", "ruff>=0.6", "mypy>=1.11", "build"]

[tool.ruff]
line-length = 120
src = ["src"]

[tool.ruff.lint]
select = ["F"]

[tool.mypy]
python_version = "3.11"
mypy_path = "src"
files = ["src/wiithon"]
warn_unused_ignores = true
disable_error_code = ["annotation-unchecked"]

[[tool.mypy.overrides]]
module = ["Crypto.*", "typer.*", "pytest.*", ]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "wiithon.builder.*",
    "wiithon.disc.*",
    "wiithon.formats.*",
    "wiithon.fst.*",
    "wiithon.ppc.*",
    "wiithon.cli",
]
ignore_errors = true

[tool.hatch.version]
path = "src/wiithon/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/wiithon"]
